services:
  postgres:
    image: postgres:16-alpine
    container_name: smarthome-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smarthome
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - smarthome-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8082:80"
    networks:
      - smarthome-network
    depends_on:
      - postgres

  temperature-api:
    build:
      context: ./temperature-api
      dockerfile: Dockerfile
    container_name: temperature-api
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - smarthome-network

  telemetry-app:
    build:
      context: ./telemetry
      dockerfile: Dockerfile
    container_name: telemetry
    ports:
      - "8083:8080"
    environment:
      - ConnectionStrings__Default=Host=postgres;Port=5432;Username=postgres;Password=postgres;Database=smarthome_telemetry
      - ConsumerConfig__BootstrapServers=kafka:9092
    restart: unless-stopped
    networks:
      - smarthome-network

  app:
    build:
      context: ./smart_home
      dockerfile: Dockerfile
    container_name: smarthome-app
    depends_on:
      postgres:
        condition: service_healthy
      temperature-api:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/smarthome
      - TEMPERATURE_API_URL=http://temperature-api:8081
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - smarthome-network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: >
        PLAINTEXT://kafka:9092,
        PLAINTEXT_HOST://0.0.0.0:29092,
        CONTROLLER://kafka:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,
        PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT,
        CONTROLLER:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkPgtfAPPLEpie4L6g
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1

    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - smarthome-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: ""
    depends_on:
      - kafka
    networks:
      - smarthome-network

volumes:
  postgres_data:
  timescaledb_data:
  kafka_data:
  

networks:
  smarthome-network:
    driver: bridge